@echo off
echo Building Jumbee.Console...
dotnet restore src\Jumbee.Console.sln
echo Building Jumbee.Console test demo project...
dotnet build tests\Jumbee.Console.TestDemo\Jumbee.Console.TestDemo.csproj /p:Configuration=Release
echo Building Jumbee.Console examples project...
dotnet build examples\Jumbee.Console.Examples\Jumbee.Console.Examples.csproj /p:Configuration=Release
echo Jumbee.Console build complete.