@echo off
echo Building Camel...
dotnet restore src\Jumbee.Console.sln
echo Building Camel test demo project...
dotnet build tests\Jumbee.Console.TestDemo\Jumbee.Console.TestDemo.csproj /p:Configuration=Release
echo Building Camel examples project...
dotnet build examples\Jumbee.Console.Examples\Jumbee.Console.Examples.csproj /p:Configuration=Release